# Generated by Django 4.2.5 on 2023-10-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AD', 'Awaiting Delivery'), ('F', 'Finished'), ('C', 'Created')], default='C', max_length=5),
        ),
    ]
