# Generated by Django 4.2.5 on 2023-10-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AD', 'Awaiting Delivery'), ('AC', 'Awaiting Customer'), ('F', 'Finished'), ('C', 'Created')], default='C', max_length=5),
        ),
    ]
